# Path
image_df_path: './Collagen_Images_Jun25.xlsx'
image_root: '/datastorage/li/CollagenRawImages'
checkpoints: './checkpoints'
results: './results'

# dataset
task: 'survival'
surv_classes: 4

# model
backbone: 'resnet18'
pretrained: 'WinKawaks/vit-tiny-patch16-224'
patch_size: 16
image_size: 1200
surv_loss: 'CE' # ['CE', 'COX', 'NLL']


# training
workers: 8
visible_gpus: '0'
seed: 42
kfold: 5
epochs: 300
batch_size: 4
lr: 2.0e-6
lr_policy: 'None'
weight_decay: 0.1
verbose: True
metric_avg: 'micro' # 'micro' or 'macro'
