# Path
image_df_path: './Collagen_Images_Jul8.xlsx'
image_root: '/datastorage/li/CollagenRawImages'
checkpoints: './checkpoints'
results: './results'

# dataset
task: 'survival'
surv_classes: 4
include: 'both' # 'stroma', 'tumour', 'both'

# model
backbone: 'CustomCNN'
pretrained: 'WinKawaks/vit-tiny-patch16-224'
patch_size: 16
image_size: 1200
surv_loss: 'hit' # ['CE', 'COX', 'NLL', 'HIT']
freeze: False


# training
workers: 0
visible_gpus: '1'
optimizer: 'AdamW'
seed: 42
kfold: 5
epochs: 50
batch_size: 48
lr: 2.0e-4
lr_policy: 'cosine'
weight_decay: 0.01
verbose: True
metric_avg: 'micro' # 'micro' or 'macro'
