# Path
image_df_path: './Collagen_Images_Jun12.xlsx'
image_root: '/datastorage/li/Collagen/Segmented'
checkpoints: './checkpoints'
results: './results'

# dataset
task: 'survival' # ['2_cls', '4_cls', 'survival']
surv_classes: 4

# model
backbone: 'resnet18'
pretrained: True
size: 256
surv_loss: 'CE' # ['CE', 'COX', 'NLL']


# training
workers: 8
visible_gpus: '0'
seed: 42
kfold: 5
epochs: 500
batch_size: 72
lr: 2.0e-6
lr_policy: 'None'
weight_decay: 0.01
verbose: True
metric_avg: 'micro' # 'micro' or 'macro'
